### ISSUE TITLE
Use ScreenUtils.clear in classic template

### ISSUE THREAD

**Issue by SonicGDX** [tommyettinger/jbump#16]
This might be in other templates too, but I noticed in the classic template of liftoff that to clear the screen, this code is used:
```
Gdx.gl.glClearColor(0.15f, 0.15f, 0.2f, 1f);
Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
```

gdx-setup on the other hand, uses `ScreenUtils.clear()` [instead](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/core/src/MainClass) and I think that is a much better way to do it. It's easier to understand, uses one less line of code and is consistent with the [libgdx.com tutorial](https://libgdx.com/wiki/start/a-simple-game).

I'm unaware of any advantages with using the gl methods directly as ScreenUtils.clear appears to call those anyway.
```
public static void clear (float r, float g, float b, float a, boolean clearDepth) {
		Gdx.gl.glClearColor(r, g, b, a);
		int mask = GL20.GL_COLOR_BUFFER_BIT;
		if (clearDepth) mask = mask | GL20.GL_DEPTH_BUFFER_BIT;
		Gdx.gl.glClear(mask);
}
```

whoops, wrong project, meant for gdx-liftoff

**Comment by tommyettinger** [comment]
It's still a good fix to make. I have it in some of my repos because a handful are compatible with much older libGDX versions (anim8-gdx comes to mind).
